import 'dotenv/config';
import express from 'express';
import PDFDocument from 'pdfkit';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { GoogleGenAI } from '@google/genai';
const __dirname=path.dirname(fileURLToPath(import.meta.url));
const app=express();app.use(express.json({limit:'8mb'}));app.use(express.static(__dirname));
const gemini=process.env.GEMINI_API_KEY?new GoogleGenAI({apiKey:process.env.GEMINI_API_KEY}):null;
const MODEL=process.env.GEMINI_MODEL||'gemini-3.6-flash';const FALLBACK_MODEL=process.env.GEMINI_FALLBACK_MODEL||'';
const IN_PRICE=Number(process.env.GEMINI_INPUT_USD_PER_MILLION||0),OUT_PRICE=Number(process.env.GEMINI_OUTPUT_USD_PER_MILLION||0);
const agents=[
['research','Pesquisa','Analise mercado, concorrentes, tendências e oportunidades.',['pesquisa','mercado','concorrente','tendência']],['strategy','Estratégia','Transforme pesquisa em objetivo, público, oferta, posicionamento e plano.',['estratégia','estrategia','objetivo','posicionamento']],['creative','Criativo','Crie conceitos visuais, formatos, roteiros e direção das peças.',['criativo','visual','arte']],['copy','Copywriter','Escreva headlines, anúncios, legendas, CTAs e mensagens de conversão.',['copy','headline','legenda']],['social','Social Media','Monte calendário, formatos, distribuição e conteúdo para redes sociais.',['social','instagram','facebook','conteúdo']],['performance','Performance','Estruture mídia paga, públicos, orçamento, testes e KPIs.',['performance','mídia','kpi','anúncio']],['seo','SEO','Defina palavras-chave, conteúdo e oportunidades orgânicas.',['seo','google','busca','orgânico']],['crm','CRM','Crie jornada, WhatsApp, follow-ups, recuperação e segmentações.',['crm','whatsapp','follow-up']],['analytics','Analytics','Defina tracking, eventos, métricas, metas e painel.',['analytics','dados','métrica','tracking']],['growth','Growth','Priorize experimentos de crescimento por impacto, confiança e esforço.',['growth','crescimento','experimento','teste']],['legal','Jurídico','Revise LGPD, publicidade, claims, direitos autorais, termos e riscos regulatórios.',['jurídico','juridico','lgpd','legal','contrato','direito']],['traffic','Tráfego Pago','Planeje Meta Ads e Google Ads, públicos, estrutura, orçamento, testes e otimização.',['tráfego','trafego','meta ads','google ads','ads']],['cro','Conversão','Otimize landing pages, funil, checkout, UX, CTA e taxa de conversão.',['conversão','conversao','landing','checkout','funil']],['offer','Produto e Oferta','Estruture proposta de valor, preço, pacotes, diferenciais e mecanismos de oferta.',['produto','oferta','preço','preco','valor']],['competitive','Inteligência Competitiva','Mapeie concorrentes, diferenciais, lacunas e oportunidades de posicionamento.',['competitivo','benchmark']],['video','Vídeo e UGC','Crie roteiros para Reels, TikTok, Shorts, UGC e anúncios em vídeo.',['vídeo','video','reels','tiktok','ugc']],['influencer','Influencer','Estruture estratégia de creators, seleção, briefing, entregas e avaliação.',['influencer','creator','influenciador']],['reputation','Reputação','Analise reviews, comentários, percepção da marca e prevenção de crises.',['reputação','reputacao','review','crise']],['local','Local e Geo','Crie estratégia regional, Google Business, mapas e campanhas geolocalizadas.',['local','regional','google business','geolocalização']],['experiments','Experimentação','Crie hipóteses, A/B tests, priorização e plano de aprendizagem.',['ab','a/b','experimento','hipótese','hipotese']]
];
const send=(res,event,data)=>res.write(`event: ${event}\ndata: ${JSON.stringify(data)}\n\n`);const clean=s=>String(s??'').replace(/\u0000/g,'');const sleep=ms=>new Promise(r=>setTimeout(r,ms));
function estimate(t){return Math.max(1,Math.ceil(String(t||'').length/4));}
function chooseAgents(brief){const b=brief.toLowerCase(),core=new Set(['research','strategy','creative','copy','performance','analytics','growth']);agents.map(a=>({a,score:a[3].reduce((n,k)=>n+(b.includes(k)?1:0),0)})).filter(x=>x.score>0).sort((a,b)=>b.score-a.score).slice(0,13).forEach(x=>core.add(x.a[0]));return agents.filter(a=>core.has(a[0]));}
function friendly(e){const s=e?.status||e?.error?.code,m=String(e?.message||'').toLowerCase();if(s===429||m.includes('quota')||m.includes('rate limit'))return 'Limite de uso da IA atingido. Tente novamente em instantes.';if(s===503||m.includes('unavailable')||m.includes('high demand'))return 'Serviço de IA temporariamente congestionado. O sistema tentou recuperar automaticamente.';if(s===401||s===403||m.includes('api key'))return 'A conexão com a IA foi recusada. Verifique a chave no servidor.';return 'O agente encontrou um erro e a operação registrou a falha.';}
function retryable(e){const s=e?.status||e?.error?.code,m=String(e?.message||'').toLowerCase();return [429,500,502,503,504].includes(s)||/unavailable|high demand|rate limit|temporarily/.test(m);}
async function ask(prompt,maxOutputTokens=2200){if(!gemini)throw new Error('GEMINI_API_KEY não configurada no servidor.');const models=[MODEL,FALLBACK_MODEL].filter((x,i,a)=>x&&a.indexOf(x)===i);let last;for(const model of models)for(let attempt=0;attempt<2;attempt++){try{const r=await gemini.models.generateContent({model,contents:prompt,config:{maxOutputTokens}}),u=r.usageMetadata||{};return{text:clean(r.text||'Sem conteúdo.'),inputTokens:Number(u.promptTokenCount||u.inputTokenCount||estimate(prompt)),outputTokens:Number(u.candidatesTokenCount||u.outputTokenCount||estimate(r.text||'')),model};}catch(e){last=e;if(!retryable(e))throw e;if(attempt===0)await sleep(900);}}throw last;}
async function runAgent(res,a,brief,context,index,total){const[id,name,role]=a;send(res,'stage',{id,name,current:index,total,status:'starting',message:`${name} foi ativado.`});send(res,'agent',{id,name,status:'working',progress:12,message:`Processando camada ${index}/${total}.`});try{const r=await ask(`Você é ${name}, especialista da MarketVerse AI.\nPapel: ${role}\n\nBRIEFING:\n${brief}\n\nCONTEXTO DISPONÍVEL:\n${context||'nenhum'}\n\nProduza uma entrega acionável, específica e verificável. Não invente fatos. Diferencie hipóteses de dados observados. Entregue recomendações práticas para o próximo agente.`,id==='legal'||id==='analytics'?1800:2200);const cost=(r.inputTokens*IN_PRICE+r.outputTokens*OUT_PRICE)/1e6;send(res,'agent',{id,name,status:'completed',progress:100,message:'Entrega concluída.',preview:r.text.slice(0,280),tokens:{input:r.inputTokens,output:r.output,total:r.inputTokens+r.outputTokens,costUsd:cost},model:r.model});return{...r,failed:false,cost};}catch(e){const msg=friendly(e);send(res,'agent',{id,name,status:'error',progress:100,message:msg,tokens:{input:0,output:0,total:0,costUsd:0}});return{text:`${name}: ${msg}`,inputTokens:0,outputTokens:0,failed:true,cost:0};}}
app.get('/api/health',(req,res)=>res.json({ok:true,service:'marketverse-ai',availableAgents:20,modelConfigured:Boolean(gemini)}));
app.get('/api/campaign/stream',async(req,res)=>{res.setHeader('Content-Type','text/event-stream');res.setHeader('Cache-Control','no-cache');res.setHeader('Connection','keep-alive');res.flushHeaders?.();const brief=clean(req.query.brief||'').trim();if(!brief){send(res,'error',{message:'Briefing vazio.'});return res.end()}const selected=chooseAgents(brief),started=Date.now();send(res,'campaign',{status:'started',agents:20,activeAgents:selected.length,availableAgents:20,stages:selected.map(a=>a[0]),routing:'nexus'});send(res,'log',{from:'coordinator',message:`NEXUS selecionou ${selected.length} especialistas entre 20 agentes disponíveis.`});let context='',results=[];for(let i=0;i<selected.length;i++){const r=await runAgent(res,selected[i],brief,context.slice(-24000),i+1,selected.length);results.push({id:selected[i][0],name:selected[i][1],role:selected[i][2],...r});context+=`\n### ${selected[i][1]}\n${r.text}`;context=context.slice(-40000);send(res,'handoff',{from:selected[i][0],to:selected[i+1]?.[0]||'coordinator',message:`${selected[i][1]} enviou dados para a próxima camada.`})}let synthesis={text:'',inputTokens:0,outputTokens:0};try{synthesis=await ask(`Você é NEXUS, coordenador da MarketVerse AI. Consolide uma estratégia executável usando o briefing e as entregas dos especialistas. Gere: resumo executivo, objetivo, público, oferta, posicionamento, conteúdo, criativos, copys, tráfego pago, SEO, CRM, jurídico/riscos quando aplicável, tracking/KPIs, experimentos, cronograma e checklist. Não invente resultados.\n\nBRIEFING:\n${brief}\n\nENTREGAS:\n${context}`,5200)}catch(e){synthesis={text:`Falha na consolidação: ${friendly(e)}`,inputTokens:0,outputTokens:0}}const totals=results.reduce((x,r)=>({input:x.input+(r.inputTokens||0),output:x.output+(r.outputTokens||0),cost:x.cost+(r.cost||0)}),{input:0,output:0,cost:0});totals.input+=synthesis.inputTokens;totals.output+=synthesis.outputTokens;totals.cost+=(synthesis.inputTokens*IN_PRICE+synthesis.outputTokens*OUT_PRICE)/1e6;const failed=results.filter(r=>r.failed).length;send(res,'coordinator',{status:failed?'completed_with_errors':'completed',output:synthesis.text,tokens:{...totals,total:totals.input+totals.output,costUsd:totals.cost},selectedAgents:selected.map(a=>a[0]),availableAgents:20});send(res,'campaign',{status:failed?'completed_with_errors':'completed',durationMs:Date.now()-started,successful:results.length-failed,failed,selectedAgents:selected.length,availableAgents:20,tokens:{...totals,total:totals.input+totals.output,costUsd:totals.cost}});res.end()});
app.post('/api/campaign/pdf',(req,res)=>{const d=req.body||{},doc=new PDFDocument({size:'A4',margin:42}),chunks=[];doc.on('data',c=>chunks.push(c));doc.on('end',()=>{res.setHeader('Content-Type','application/pdf');res.setHeader('Content-Disposition','attachment; filename="marketverse-relatorio-executivo.pdf"');res.end(Buffer.concat(chunks))});doc.fillColor('#111827').fontSize(24).text('MarketVerse AI — Relatório Executivo');doc.moveDown();doc.fontSize(14).fillColor('#2563eb').text(clean(d.title||'Campanha'));doc.moveDown();doc.fontSize(10).fillColor('#374151').text(clean(d.report||d.output||'Sem relatório.'),{lineGap:3});doc.end()});
app.get('*',(req,res)=>res.sendFile(path.join(__dirname,'index.html')));const PORT=process.env.PORT||10000;app.listen(PORT,'0.0.0.0',()=>console.log(`MarketVerse AI listening on ${PORT}`));