const AGENTS=[['strategy','Estratégia','🧠','📋'],['research','Pesquisa','🔎','🔎'],['copy','Copywriter','✍️','⌨️'],['creative','Criativo','🎨','🎨'],['social','Social Media','📱','📱'],['seo','SEO','🔍','🔍'],['performance','Performance','💰','💻'],['analytics','Analytics','📊','📈'],['crm','CRM','📧','💌'],['growth','Growth','🧪','🧪']];
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const key='marketverse_campaigns_v2';let campaigns=JSON.parse(localStorage.getItem(key)||'[]');
const app=document.querySelector('#app');
app.innerHTML=`<div class="mv"><header><div class="brand"><b>✦</b><div><strong>MarketVerse AI</strong><small>HQ • Agência de marketing viva</small></div></div><nav><button class="tab active" data-tab="hq">🎮 HQ</button><button class="tab" data-tab="campaigns">📋 Campanhas <i id="count">${campaigns.length}</i></button></nav><span class="online">● 10 agentes online</span></header><section id="hq" class="view"><div class="office"><div class="floor"></div><div class="sign">MARKETVERSE HQ <em>LIVE</em></div><div class="boss"><div class="boss-avatar">🧠</div><strong>COORDENADOR</strong><span id="coord">Aguardando briefing…</span></div>${AGENTS.map((a,i)=>`<div class="station s${i}"><div class="desk">▣</div><div class="pixel" id="p-${a[0]}"><span>•ᴗ•</span><b>${a[3]}</b></div><strong>${a[1]}</strong><small id="st-${a[0]}">Aguardando</small><div class="progress"><i id="bar-${a[0]}"></i></div></div>`).join('')}</div><aside><div class="panel-title"><b>📡 Atividade</b><span>Tempo real</span></div><textarea id="brief" placeholder="Descreva a campanha… Ex.: hamburgueria em Recife, R$ 3.000, gerar pedidos pelo WhatsApp."></textarea><button id="run">▶ Iniciar campanha</button><div id="feed" class="feed"></div><div id="delivery" class="delivery hidden"></div></aside></section><section id="campaigns" class="view hidden"><div class="campaign-head"><div><small>WORKSPACE</small><h1>Campanhas</h1><p>Cada execução concluída vira uma entrega organizada.</p></div><button id="back">🎮 Voltar para HQ</button></div><div id="list" class="cards"></div></section></div>`;
const $=s=>document.querySelector(s), feed=$('#feed'), brief=$('#brief'), coord=$('#coord'), delivery=$('#delivery');
function log(icon,title,text){const e=document.createElement('div');e.className='log';e.innerHTML=`<b>${icon} ${esc(title)}</b><span>${esc(text)}</span>`;feed.prepend(e);}
function resetAgents(){AGENTS.forEach(a=>{$(`#p-${a[0]}`).classList.remove('working','done');$(`#st-${a[0]}`).textContent='Aguardando';$(`#bar-${a[0]}`).style.width='0%'})}
function save(c){campaigns.unshift(c);campaigns=campaigns.slice(0,30);localStorage.setItem(key,JSON.stringify(campaigns));$('#count').textContent=campaigns.length}
function render(){const list=$('#list');if(!campaigns.length){list.innerHTML='<div class="empty">📦<b>Nenhuma campanha ainda.</b><span>Execute uma campanha na HQ para criar sua primeira entrega.</span></div>';return}list.innerHTML=campaigns.map((c,i)=>`<article class="card"><div><b>${i?'📦':'🚀'}</b><section><h3>${esc(c.title)}</h3><small>${new Date(c.createdAt).toLocaleString('pt-BR')} • ${c.agents}/10 agentes</small></section><em>✓ Concluída</em></div><p>${esc(c.brief)}</p><footer><span>🧠 Gemini</span><span>⚡ ${esc(c.duration)}</span><button data-id="${c.id}">Ver entrega →</button></footer></article>`).join('');list.querySelectorAll('button').forEach(b=>b.onclick=()=>detail(b.dataset.id))}
function detail(id){const c=campaigns.find(x=>x.id===id);if(!c)return;$('#list').innerHTML=`<article class="detail"><button id="closeDetail">← Campanhas</button><small>ENTREGA FINAL</small><h2>${esc(c.title)}</h2><p>${esc(c.brief)}</p><pre>${esc(c.output)}</pre></article>`;$('#closeDetail').onclick=render}
function switchTab(tab){document.querySelectorAll('.tab').forEach(x=>x.classList.toggle('active',x.dataset.tab===tab));$('#hq').classList.toggle('hidden',tab!=='hq');$('#campaigns').classList.toggle('hidden',tab!=='campaigns');if(tab==='campaigns')render()}
document.querySelectorAll('.tab').forEach(b=>b.onclick=()=>switchTab(b.dataset.tab));$('#back').onclick=()=>switchTab('hq');
$('#run').onclick=()=>{const text=brief.value.trim();if(!text){brief.focus();return}resetAgents();feed.innerHTML='';delivery.classList.add('hidden');coord.textContent='Distribuindo tarefas…';log('🧠','Coordenador','Nova campanha recebida. Os agentes estão indo para suas estações.');$('#run').disabled=true;const started=Date.now();const stream=new EventSource('/api/campaign/stream?brief='+encodeURIComponent(text));
stream.addEventListener('campaign',e=>{const d=JSON.parse(e.data);if(d.status==='started'){coord.textContent=`Equipe trabalhando com ${d.provider||'IA'}…`;log('🧠','Coordenador',`10 especialistas iniciados • até ${d.agents} agentes disponíveis`)}if(d.status==='completed'){coord.textContent='Campanha pronta ✓';$('#run').disabled=false;stream.close()}});
stream.addEventListener('log',e=>{const d=JSON.parse(e.data);log('🧠','Coordenador',d.message)});
stream.addEventListener('agent',e=>{const d=JSON.parse(e.data),a=AGENTS.find(x=>x[0]===d.id);if(!a)return;const p=$(`#p-${a[0]}`),st=$(`#st-${a[0]}`);p.classList.toggle('working',d.status==='working');p.classList.toggle('done',d.status==='completed');if(d.status==='working'){p.classList.remove('walk');void p.offsetWidth;p.classList.add('walk')}st.textContent=d.message||d.status;$(`#bar-${a[0]}`).style.width=(d.progress||0)+'%';if(d.status==='completed')log(a[2],a[1],'Entregou o trabalho ao Coordenador.');if(d.status==='error')log('⚠️',a[1],d.message)});
stream.addEventListener('coordinator',e=>{const d=JSON.parse(e.data);if(d.output){delivery.classList.remove('hidden');delivery.innerHTML=`<b>📦 Entrega consolidada</b><pre>${esc(d.output)}</pre>`}if(d.status==='completed'){const title=text.split(/[.!?]/)[0].slice(0,60)||'Nova campanha';save({id:String(Date.now()),title,brief:text,output:d.output,agents:10,duration:Math.round((Date.now()-started)/1000)+'s',createdAt:new Date().toISOString()});log('📦','Campanha','Entrega salva no Workspace de Campanhas.')}});
stream.addEventListener('error',e=>{log('⚠️','Sistema',e.data?'Falha recebida do servidor.':'Conexão encerrada.');coord.textContent='Execução encerrada.';$('#run').disabled=false;stream.close()})};
render();