const agents=[
 {id:'strategy',name:'Estratégia',icon:'🧠',cls:'a1',prop:'📋'},
 {id:'research',name:'Pesquisa',icon:'🔎',cls:'a2',prop:'🔎'},
 {id:'copy',name:'Copywriter',icon:'✍️',cls:'a3',prop:'⌨️'},
 {id:'creative',name:'Criativo',icon:'🎨',cls:'a4',prop:'🎨'},
 {id:'social',name:'Social Media',icon:'📱',cls:'a5',prop:'📱'},
 {id:'seo',name:'SEO',icon:'🔍',cls:'a6',prop:'🔍'},
 {id:'performance',name:'Performance',icon:'💰',cls:'a7',prop:'💻'},
 {id:'analytics',name:'Analytics',icon:'📊',cls:'a8',prop:'📈'},
 {id:'crm',name:'CRM',icon:'📧',cls:'a9',prop:'💌'},
 {id:'growth',name:'Growth',icon:'🧪',cls:'a10',prop:'🧪'}
];
const states=Object.fromEntries(agents.map(a=>[a.id,{progress:0,status:'Aguardando',preview:''}]));
const app=document.querySelector('#app');
const character=a=>`<div class="character" aria-hidden="true"><div class="shadow"></div><div class="head"><span class="hair"></span><span class="face">•ᴗ•</span></div><div class="body"><span class="shirt"></span><span class="prop">${a.prop}</span></div><div class="legs"><i></i><i></i></div></div>`;
app.innerHTML=`<div class="shell">
<header class="topbar"><div class="brand"><div class="brand-mark">✦</div><div><strong>MarketVerse AI</strong><div class="muted">MARKETVERSE HQ • Agência de marketing viva</div></div></div><div class="live"><span id="liveDot" class="dot"></span><span id="liveCount">10 agentes online</span></div></header>
<main class="layout"><section class="war"><div class="grid"></div><div class="floor"></div><div class="office-label">MARKETVERSE HQ <span>• LIVE</span></div>
<div class="center"><div class="desk-boss"><div id="core" class="core">🧠</div><div class="boss-chair">▰</div></div><h2>COORDENADOR</h2><div id="task" class="task">Aguardando briefing…</div><div id="provider" class="provider">⚙️ Conectando ao Gemini…</div><div id="handoff" class="handoff"></div></div>
${agents.map(a=>`<article id="agent-${a.id}" class="agent ${a.cls}"><div class="desk"><div class="monitor"><span>${a.icon}</span></div><div class="desk-top"></div></div>${character(a)}<div class="agent-info"><strong>${a.name}</strong><small>Agente especializado</small></div><div class="bar"><span id="bar-${a.id}" style="width:0%"></span></div><div id="status-${a.id}" class="status">Aguardando</div><div id="result-${a.id}" class="agent-result"></div></article>`).join('')}</section>
<aside class="side"><div class="side-title"><div><h3>📡 Activity Feed</h3><span class="muted">A equipe trabalhando em tempo real</span></div><span class="mode">🎮 HQ</span></div><div class="brief"><label for="brief">Nova campanha</label><textarea id="brief" placeholder="Ex.: lançar uma campanha para uma hamburgueria em Recife, R$ 3.000, foco em pedidos."></textarea></div><div id="feed" class="feed"></div><div id="result" class="result hidden"></div><div class="controls"><button id="reset">↻ Resetar</button><button id="run" class="primary">▶ Colocar equipe para trabalhar</button></div></aside></main>
<div class="footer">🎮 HQ visual • 📋 campanhas • 📦 entregas • Gemini • eventos reais • sem exposição de raciocínio interno</div></div>`;

const feed=document.querySelector('#feed');const task=document.querySelector('#task');const brief=document.querySelector('#brief');const result=document.querySelector('#result');const provider=document.querySelector('#provider');
function agentById(id){return agents.find(a=>a.id===id)}
function addEvent(icon,name,text){const el=document.createElement('div');el.className='event';el.innerHTML=`<b>${icon} ${escapeHtml(name)}</b><p>${escapeHtml(text)}</p>`;feed.prepend(el);while(feed.children.length>18)feed.lastChild.remove()}
function showHandoff(agent){const handoff=document.querySelector('#handoff');handoff.innerHTML=`<span class="packet">${agent.icon}</span><span>${agent.name} → 🧠 Coordenador</span>`;handoff.classList.remove('show');void handoff.offsetWidth;handoff.classList.add('show');setTimeout(()=>handoff.classList.remove('show'),1900)}
function reset(){agents.forEach(a=>{states[a.id]={progress:0,status:'Aguardando',preview:''};document.querySelector(`#bar-${a.id}`).style.width='0%';document.querySelector(`#status-${a.id}`).textContent='Aguardando';document.querySelector(`#result-${a.id}`).innerHTML='';document.querySelector(`#agent-${a.id}`).classList.remove('active','done','error')});feed.innerHTML='<div class="event"><b>🧠 Coordenador</b><p>HQ pronta. Informe um briefing e coloque a equipe para trabalhar.</p></div>';result.classList.add('hidden');result.innerHTML='';task.textContent='Aguardando briefing…';document.querySelector('#core').classList.remove('active');document.querySelector('#run').disabled=false;document.querySelector('#liveCount').textContent='10 agentes online';document.querySelector('#handoff').innerHTML=''}
function handleAgent(data){const a=agentById(data.id);if(!a)return;const s=states[data.id];s.progress=data.progress??s.progress;s.status=data.status;s.preview=data.preview||s.preview;document.querySelector(`#bar-${a.id}`).style.width=s.progress+'%';document.querySelector(`#status-${a.id}`).textContent=data.message||data.status;const card=document.querySelector(`#agent-${a.id}`);card.classList.toggle('active',data.status==='working');card.classList.toggle('done',data.status==='completed');card.classList.toggle('error',data.status==='error');if(data.preview){document.querySelector(`#result-${a.id}`).innerHTML=`<span>✓ Entrega</span><p>${escapeHtml(data.preview)}</p>`;showHandoff(a)}if(data.message)addEvent(a.icon,a.name,data.message)}
async function checkHealth(){try{const r=await fetch('/api/health');const d=await r.json();if(d.geminiConfigured){provider.textContent=`🟢 Gemini conectado • ${d.agents} agentes disponíveis`;provider.classList.add('ok')}else{provider.textContent='🔴 Gemini não configurado no servidor';provider.classList.add('error')}}catch{provider.textContent='🟠 Não foi possível verificar o provedor'}}
function run(){const text=brief.value.trim();if(!text){brief.focus();task.textContent='Escreva um briefing antes de executar.';return}reset();document.querySelector('#run').disabled=true;document.querySelector('#core').classList.add('active');task.textContent='Coordenador distribuindo tarefas…';addEvent('🧠','Coordenador','Briefing recebido. Os personagens estão indo para suas estações.');
const stream=new EventSource(`/api/campaign/stream?brief=${encodeURIComponent(text)}`);
stream.addEventListener('campaign',e=>{const d=JSON.parse(e.data);if(d.status==='started'){task.textContent=`10 agentes executando com ${d.provider||'IA'}…`;provider.textContent=`🟢 ${d.provider||'IA'} conectado • ${d.agents} agentes`;provider.classList.add('ok');addEvent('🧠','Coordenador','Equipe distribuída. Cada especialista está trabalhando na sua estação.')}if(d.status==='completed'){task.textContent='Campanha consolidada pelo Coordenador ✓';stream.close();document.querySelector('#core').classList.remove('active');document.querySelector('#run').disabled=false;addEvent('📦','Campanha','Entrega final pronta na HQ.')}});
stream.addEventListener('log',e=>{const d=JSON.parse(e.data);addEvent('🧠','Coordenador',d.message)});
stream.addEventListener('agent',e=>{const d=JSON.parse(e.data);handleAgent(d);const done=agents.filter(a=>states[a.id].status==='completed').length;document.querySelector('#liveCount').textContent=`${done}/10 entregas concluídas`});
stream.addEventListener('coordinator',e=>{const d=JSON.parse(e.data);if(d.output){result.classList.remove('hidden');result.innerHTML=`<div class="result-head"><span>📦</span><strong>Entrega da campanha</strong></div><pre>${escapeHtml(d.output)}</pre>`}if(d.status==='completed')addEvent('🧠','Coordenador','Recebeu os relatórios e montou a entrega final.')}});
stream.addEventListener('error',e=>{if(e.data){try{const d=JSON.parse(e.data);addEvent('⚠️','Sistema',d.message);task.textContent='A execução encontrou um erro.'}catch{task.textContent='A execução encontrou um erro.'}}else{task.textContent='Conexão encerrada.'}stream.close();document.querySelector('#run').disabled=false;document.querySelector('#core').classList.remove('active')})}
function escapeHtml(s){return String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
document.querySelector('#run').onclick=run;document.querySelector('#reset').onclick=reset;reset();checkHealth();