const AGENTS=[['research','Pesquisa','RS'],['strategy','Estratégia','ST'],['creative','Criativo','CR'],['copy','Copywriter','CP'],['social','Social Media','SM'],['performance','Performance','PF'],['seo','SEO','SE'],['crm','CRM','CM'],['analytics','Analytics','AN'],['growth','Growth','GR']];
const LAYERS=[['INPUT SIGNAL',12],['CONTEXT',27],['PATTERN',42],['SYNTHESIS',57],['AGENTS',73],['OUTPUT',88]];
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const app=document.querySelector('#app');if(!app)throw new Error('MarketVerse: #app não encontrado');
const state=Object.fromEntries(AGENTS.map(a=>[a[0],{status:'idle',message:'Aguardando'}]));let stream=null,selected='coordinator',start=0,done=0,failed=0;
const layerNodes=[];for(let l=0;l<6;l++){const count=l===0?7:l===5?7:10;for(let i=0;i<count;i++){layerNodes.push({id:`L${l}N${i}`,x:12+l*15.2,y:18+(i+1)*(64/(count+1)),layer:l})}}
const agentNodes=AGENTS.map((a,i)=>({id:a[0],x:12+4.8*(i%10),y:80+(i%2)*7}));
const allNodes=[...layerNodes,...agentNodes];
const links=[];for(let l=0;l<5;l++){const from=layerNodes.filter(n=>n.layer===l),to=layerNodes.filter(n=>n.layer===l+1);from.forEach((a,i)=>to.forEach((b,j)=>{if(Math.abs(i-j)<=2)links.push([a,b])}));}
const svgLinks=links.map((p,i)=>`<path class="deep-edge" id="deep-${i}" data-a="${p[0].id}" data-b="${p[1].id}" d="M${p[0].x*10} ${p[0].y*7} C${p[0].x*10+45} ${p[0].y*7},${p[1].x*10-45} ${p[1].y*7},${p[1].x*10} ${p[1].y*7}"/>`).join('');
const svgNodes=layerNodes.map(n=>`<i class="deep-neuron" id="${n.id}" style="left:${n.x}%;top:${n.y}%"></i>`).join('');
const agentCards=AGENTS.map((a,i)=>`<article class="agent-card" id="agent-${a[0]}" data-agent="${a[0]}" style="left:${12+8.45*i}%;top:91%"><span>${a[2]}</span><b>${a[1]}</b><i id="agent-dot-${a[0]}"></i><em id="agent-bar-${a[0]}"></em></article>`).join('');
app.innerHTML=`<div class="neural-shell"><header class="neural-top"><div class="neural-brand"><div class="neural-brand-mark">✦</div><div><strong>MarketVerse AI</strong><small>DEEP AI PROCESSING VISUALIZATION</small></div></div><div class="processing-badge" id="mode">SIMULATION + LIVE AGENT EVENTS</div><span class="neural-live" id="live">● SYSTEM READY</span></header><main class="neural-layout"><section class="deep-canvas"><div class="deep-title"><small>AI PROCESSING CORE</small><h1>Observe the intelligence flow</h1><p>Representação visual inspirada em redes neurais. As partículas e ativações refletem o processamento e os eventos reais dos agentes — não os neurônios internos do modelo.</p></div><div class="layer-labels">${LAYERS.map(x=>`<span style="left:${x[1]}%">${x[0]}</span>`).join('')}</div><div class="deep-map"><svg class="deep-svg" viewBox="0 0 1000 700" preserveAspectRatio="none"><defs><filter id="neon"><feGaussianBlur stdDeviation="2.5" result="b"/><feMerge><feMergeNode in="b"/><feMergeNode in="SourceGraphic"/></feMerge></filter><radialGradient id="core"><stop offset="0"/><stop offset="1"/></radialGradient></defs>${svgLinks}</svg>${svgNodes}<div class="core-orb" id="core"><div>AI</div><small>PROCESSING CORE</small></div>${agentCards}<div class="input-pill">INPUT • BRIEFING</div><div class="output-pill">OUTPUT • CAMPAIGN</div><div id="particles"></div></div><div class="deep-stats"><span><b id="pathways">0</b> active pathways</span><span><b id="signals">0</b> signals</span><span><b id="depth">6</b> visual layers</span><span><b id="sync">0/10</b> agents synchronized</span></div></section><aside class="neural-inspector"><div class="inspector-title">OPERATION CONTROL</div><div class="inspector-card"><h2 id="name">NEXUS</h2><p id="text">A rede está pronta. Inicie uma operação para observar a ativação visual e o trabalho real dos agentes.</p><div class="inspector-grid"><div class="inspector-metric"><b id="done">0</b><small>Concluídos</small></div><div class="inspector-metric"><b id="active">0</b><small>Ativos</small></div><div class="inspector-metric"><b id="failed">0</b><small>Falhas</small></div><div class="inspector-metric"><b id="time">0s</b><small>Tempo</small></div></div></div><div class="operation-box"><label>BRIEFING DA OPERAÇÃO</label><textarea id="brief" placeholder="Ex.: Criar campanha para uma academia de Jiu-Jitsu em Recife..."></textarea><button class="run-neural" id="run">🚀 Iniciar processamento</button></div><div class="neural-feed" id="feed"><div class="neural-log">Os eventos reais do pipeline aparecerão aqui.</div></div></aside></main></div>`;
const $=s=>document.querySelector(s),feed=$('#feed');
function log(title,msg){const e=document.createElement('div');e.className='neural-log';e.innerHTML=`<b>${esc(title)}</b><br>${esc(msg)}`;feed.prepend(e)}
function select(id){selected=id;const s=id==='coordinator'?{message:'NEXUS — coordenador central'}:state[id];$('#name').textContent=id==='coordinator'?'NEXUS':(AGENTS.find(x=>x[0]===id)?.[1]||id);$('#text').textContent=s?.message||''}
function setAgent(id,status,progress,msg){if(!state[id])return;state[id]={status,message:msg||''};const card=$(`#agent-${id}`);if(card){card.classList.remove('working','done','error');if(status==='working')card.classList.add('working');if(status==='completed')card.classList.add('done');if(status==='error'||status==='failed')card.classList.add('error')}const bar=$(`#agent-bar-${id}`);if(bar)bar.style.width=Math.max(0,Math.min(100,progress||0))+'%';if(selected===id)select(id)}
function reset(){AGENTS.forEach(a=>setAgent(a[0],'idle',0,'Aguardando'));document.querySelectorAll('.deep-edge').forEach(e=>e.classList.remove('active','done'));document.querySelectorAll('.deep-neuron').forEach(e=>e.classList.remove('firing'));document.querySelectorAll('.particle').forEach(e=>e.remove());$('#core').classList.remove('processing','complete','error');done=failed=0;$('#done').textContent=0;$('#failed').textContent=0;$('#active').textContent=0;$('#sync').textContent='0/10';$('#pathways').textContent=0;$('#signals').textContent=0}
function activateNetwork(intensity=1){document.querySelectorAll('.deep-neuron').forEach((n,i)=>{if(Math.random()<.38*intensity){n.classList.add('firing');setTimeout(()=>n.classList.remove('firing'),300+Math.random()*900)}});const edges=[...document.querySelectorAll('.deep-edge')];edges.forEach((e,i)=>{if(Math.random()<.16*intensity){e.classList.add('active');setTimeout(()=>e.classList.remove('active'),900+Math.random()*1400)}});$('#pathways').textContent=Math.round(35*intensity+Math.random()*80);$('#signals').textContent=Math.round(100+Math.random()*900)}
function particle(){const p=document.createElement('i');p.className='particle';p.style.left=(8+Math.random()*84)+'%';p.style.top=(15+Math.random()*67)+'%';$('#particles').appendChild(p);p.animate([{transform:'translate(0,0) scale(.4)',opacity:0},{transform:'translate(80px,-20px) scale(1)',opacity:1},{transform:'translate(170px,10px) scale(.2)',opacity:0}],{duration:900+Math.random()*900,easing:'ease-in-out'}).onfinish=()=>p.remove()}
function pulseLoop(){if(!$('#run').disabled)return;activateNetwork(.8);for(let i=0;i<5;i++)setTimeout(particle,i*110);setTimeout(pulseLoop,700)}
AGENTS.forEach(a=>document.querySelector(`#agent-${a[0]}`)?.addEventListener('click',()=>select(a[0])));
$('#run').addEventListener('click',()=>{const brief=$('#brief').value.trim();if(!brief){$('#brief').focus();return}stream?.close();reset();start=Date.now();$('#run').disabled=true;$('#live').textContent='● AI PROCESSING';$('#live').style.color='#4de8ff';$('#core').classList.add('processing');feed.innerHTML='';log('NEXUS','Briefing recebido. Ativando representação de processamento e pipeline multiagente...');pulseLoop();stream=new EventSource('/api/campaign/stream?brief='+encodeURIComponent(brief));
stream.addEventListener('campaign',e=>{const d=JSON.parse(e.data);if(d.status==='started'){log('NEXUS',`Operação iniciada • ${d.agents||10} agentes sincronizados no pipeline.`)}if(d.status==='completed'||d.status==='completed_with_errors'){const sec=Math.round((Date.now()-start)/1000);$('#time').textContent=sec+'s';$('#live').textContent=d.status==='completed'?'● PROCESSING COMPLETE':'● COMPLETE WITH ERRORS';$('#live').style.color=d.status==='completed'?'#61f2a5':'#ffc857';$('#run').disabled=false;$('#core').classList.remove('processing');$('#core').classList.add(d.status==='completed'?'complete':'error');stream?.close()}});
stream.addEventListener('stage',e=>{const d=JSON.parse(e.data);if(state[d.id]){setAgent(d.id,'working',15,d.name+' foi acionado.');$('#active').textContent=Object.values(state).filter(x=>x.status==='working').length;$('#sync').textContent=`${Object.values(state).filter(x=>x.status!=='idle').length}/10`;log(d.name,d.message||'Processando...');activateNetwork(1.3);for(let i=0;i<7;i++)setTimeout(particle,i*90)}});
stream.addEventListener('agent',e=>{const d=JSON.parse(e.data);if(!state[d.id])return;setAgent(d.id,d.status,d.progress,d.message);if(d.status==='completed'){done++;for(let i=0;i<10;i++)setTimeout(particle,i*55)}if(d.status==='error'||d.status==='failed'){failed++;log('⚠ '+d.name,d.message||'Falha')}$('#done').textContent=done;$('#failed').textContent=failed;$('#active').textContent=Object.values(state).filter(x=>x.status==='working').length;$('#sync').textContent=`${Object.values(state).filter(x=>x.status!=='idle').length}/10`});
stream.addEventListener('handoff',e=>{const d=JSON.parse(e.data);log('HANDOFF',`${String(d.from||'agent').toUpperCase()} → ${String(d.to||'coordinator').toUpperCase()}`);activateNetwork(1.8);for(let i=0;i<14;i++)setTimeout(particle,i*45)});
stream.addEventListener('coordinator',e=>{const d=JSON.parse(e.data);$('#core').classList.remove('processing');$('#core').classList.add(d.status==='error'?'error':'complete');select('coordinator');$('#text').textContent=d.output||'Consolidação finalizada.';log('NEXUS',d.status==='completed_with_errors'?`Finalizada com ${d.failed||0} falha(s).`:'Processamento consolidado. Relatório e kit disponíveis.');if(d.report){const button=document.createElement('button');button.className='report-btn';button.textContent='📄 Gerar PDF executivo';button.onclick=async()=>{button.disabled=true;button.textContent='Gerando PDF...';try{const r=await fetch('/api/campaign/pdf',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({title:$('#brief').value.slice(0,80),report:d.report})});if(!r.ok)throw new Error('PDF');const blob=await r.blob();const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='marketverse-relatorio-executivo.pdf';a.click();URL.revokeObjectURL(a.href);button.textContent='✓ PDF executivo pronto'}catch(err){button.disabled=false;button.textContent='📄 Gerar PDF executivo';log('PDF','Não foi possível gerar o relatório.')}};feed.prepend(button)}});
stream.addEventListener('error',e=>{let d={};try{d=JSON.parse(e.data)}catch{}log('ERRO',d.message||'Falha na execução.');$('#live').textContent='● PROCESSING ERROR';$('#live').style.color='#ff667a';$('#run').disabled=false;$('#core').classList.remove('processing');$('#core').classList.add('error');stream?.close()})});
setInterval(()=>{if(start&&$('#run').disabled)$('#time').textContent=Math.round((Date.now()-start)/1000)+'s'},1000);