const AGENTS=[['research','Pesquisa'],['strategy','Estratégia'],['creative','Criativo'],['copy','Copywriter'],['social','Social Media'],['performance','Performance'],['seo','SEO'],['crm','CRM'],['analytics','Analytics'],['growth','Growth'],['legal','Jurídico'],['traffic','Tráfego Pago'],['cro','Conversão'],['offer','Produto e Oferta'],['competitive','Inteligência Competitiva'],['video','Vídeo e UGC'],['influencer','Influencer'],['reputation','Reputação'],['local','Local e Geo'],['experiments','Experimentação']];
const $=s=>document.querySelector(s),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const state=Object.fromEntries(AGENTS.map(a=>[a[0],{status:'idle',tokens:0}]));let stream=null,start=0,totalTokens=0,inputTokens=0,outputTokens=0,cost=0,done=0,failed=0,flowTimer=null;
const positions=AGENTS.map((a,i)=>({x:8+(i%10)*9.2,y:18+Math.floor(i/10)*63}));
const layerX=[8,18,28,38,48,58,68,78,88];
const neurons=Array.from({length:360},(_,i)=>{const layer=i%9;const row=Math.floor(i/9)%40;const jitter=((i*37)%100)/100;return `<i class="deep-neuron" data-n="${i}" data-layer="${layer}" style="left:${layerX[layer]+(jitter-.5)*1.8}%;top:${10+row*2.05}%"></i>`}).join('');
const connections=Array.from({length:280},(_,i)=>{const l=i%8;const row=Math.floor(i/8)%35;const x1=layerX[l],x2=layerX[l+1],y1=12+row*2.1,y2=12+((row*7+i)%35)*2.1;return `<path class="deep-synapse" data-layer="${l}" d="M${x1*10} ${y1*7} C${(x1+3)*10} ${y1*7},${(x2-3)*10} ${y2*7},${x2*10} ${y2*7}"/>`}).join('');
if(!$('#app'))throw new Error('MarketVerse: #app não encontrado');
$('#app').innerHTML=`<div class="neural-shell"><header class="neural-top"><div class="neural-brand"><div class="neural-brand-mark">✦</div><div><strong>MarketVerse AI</strong><small>DEEP AI PROCESSING CENTER</small></div></div><div class="processing-badge">20 AGENTES • LIVE NEURAL SIMULATION</div><span class="neural-live" id="live">● SYSTEM READY</span></header><main class="neural-layout"><section class="deep-canvas"><div class="deep-title"><small>NEURAL PROCESSING VISUALIZATION</small><h1>Inteligência em processamento</h1><p>Uma representação visual inspirada em redes neurais. As ativações são sincronizadas com os eventos reais da operação.</p></div><div class="deep-map"><div class="layer-labels"><span style="left:8%">INPUT</span><span style="left:28%">FEATURES</span><span style="left:48%">DEEP PATTERNS</span><span style="left:68%">SYNTHESIS</span><span style="left:88%">AGENTS</span></div><svg class="deep-svg" viewBox="0 0 1000 700" preserveAspectRatio="none"><defs><filter id="glow"><feGaussianBlur stdDeviation="2.5" result="b"/><feMerge><feMergeNode in="b"/><feMergeNode in="SourceGraphic"/></feMerge></filter></defs>${connections}</svg>${neurons}<div class="input-pulse"><span>INPUT</span><b>BRIEFING</b></div><div class="core-orb"><b>🧠</b><strong>NEXUS</strong><small>AI CORE</small><em></em></div>${AGENTS.map((a,i)=>`<article class="deep-agent" id="a-${a[0]}" style="left:${positions[i].x}%;top:${positions[i].y}%"><span>${String(i+1).padStart(2,'0')}</span><b>${a[1]}</b><i></i><small id="t-${a[0]}">aguardando</small></article>`).join('')}</div><div class="neural-disclaimer">VISUALIZAÇÃO INSPIRADA EM REDES NEURAIS • NÃO REPRESENTA OS PESOS OU O RACIOCÍNIO INTERNO DO MODELO</div></section><aside class="neural-inspector"><div class="inspector-title">OPERATION TELEMETRY</div><div class="inspector-card"><h2 id="focus">NEXUS</h2><p id="message">Inicie uma operação para acompanhar a propagação dos sinais e o consumo real de tokens.</p><div class="inspector-grid"><div class="inspector-metric"><b id="active">0</b><small>Ativos</small></div><div class="inspector-metric"><b id="done">0</b><small>Concluídos</small></div><div class="inspector-metric"><b id="tok">0</b><small>Tokens</small></div><div class="inspector-metric"><b id="time">0s</b><small>Tempo</small></div></div></div><div class="token-panel"><div><span>INPUT</span><b id="tin">0</b></div><div><span>OUTPUT</span><b id="tout">0</b></div><div><span>CUSTO ESTIMADO</span><b id="cost">$0.000000</b></div><div><span>ATIVAÇÕES</span><b id="activations">0</b></div></div><div class="operation-box"><label>BRIEFING</label><textarea id="brief" placeholder="Descreva a campanha..."></textarea><button class="run-neural" id="run">🚀 Iniciar processamento</button></div><div class="neural-feed" id="feed"></div></aside></main></div>`;
const feed=$('#feed');let activationCount=0;
function log(t,m){const e=document.createElement('div');e.className='neural-log';e.innerHTML=`<b>${esc(t)}</b><br>${esc(m)}`;feed.prepend(e)}
function activate(id,d){const el=$('#a-'+id);if(!el)return;el.classList.remove('working','done','error');if(d)el.classList.add(d);const t=$('#t-'+id);if(t)t.textContent=d==='working'?'processando':d==='done'?'concluído':d==='error'?'erro':'aguardando'}
function wave(layer=null){activationCount++;$('#activations').textContent=activationCount.toLocaleString('pt-BR');const ns=[...document.querySelectorAll('.deep-neuron')];const ss=[...document.querySelectorAll('.deep-synapse')];const target=layer==null?null:Number(layer);ns.forEach((n,i)=>{if(target!==null&&Number(n.dataset.layer)!==target)return;setTimeout(()=>{n.classList.add('firing');setTimeout(()=>n.classList.remove('firing'),650)},(i%32)*18)});ss.forEach((s,i)=>{if(target!==null&&Number(s.dataset.layer)!==target)return;s.classList.add('transmitting');setTimeout(()=>s.classList.remove('transmitting'),900)});const core=$('.core-orb');core?.classList.add('thinking');setTimeout(()=>core?.classList.remove('thinking'),900)}
function startAmbient(){clearInterval(flowTimer);flowTimer=setInterval(()=>{if(!stream)wave(Math.floor(Math.random()*8))},2200)}
function update(){const active=Object.values(state).filter(x=>x.status==='working').length;$('#active').textContent=active;$('#done').textContent=done;$('#tok').textContent=totalTokens.toLocaleString('pt-BR');$('#tin').textContent=inputTokens.toLocaleString('pt-BR');$('#tout').textContent=outputTokens.toLocaleString('pt-BR');$('#cost').textContent='$'+cost.toFixed(6);if(start)$('#time').textContent=Math.round((Date.now()-start)/1000)+'s'}
function reset(){AGENTS.forEach(a=>{state[a[0]]={status:'idle',tokens:0};activate(a[0],'')});done=failed=totalTokens=inputTokens=outputTokens=cost=activationCount=0;$('#activations').textContent='0';feed.innerHTML='';update()}
$('#run').onclick=()=>{const brief=$('#brief').value.trim();if(!brief)return $('#brief').focus();stream?.close();reset();start=Date.now();$('#run').disabled=true;$('#live').textContent='● PROCESSING';$('#live').style.color='#55e8ff';log('NEXUS','Analisando briefing e iniciando propagação neural...');wave();stream=new EventSource('/api/campaign/stream?brief='+encodeURIComponent(brief));
stream.addEventListener('campaign',e=>{const d=JSON.parse(e.data);$('#message').textContent=`NEXUS ativou ${d.activeAgents} de ${d.availableAgents} agentes disponíveis.`;log('NEXUS',`Roteamento: ${d.activeAgents}/${d.availableAgents} agentes selecionados.`);wave()});
stream.addEventListener('stage',e=>{const d=JSON.parse(e.data);activate(d.id,'working');wave(Math.floor(Math.random()*8));$('#focus').textContent=d.name;$('#message').textContent=d.message||'Processando...';log(d.name,'Agente ativado • sinal propagando pela rede.');update()});
stream.addEventListener('agent',e=>{const d=JSON.parse(e.data);if(!state[d.id])return;state[d.id].status=d.status;activate(d.id,d.status==='working'?'working':d.status==='completed'?'done':'error');if(d.tokens){inputTokens+=d.tokens.input||0;outputTokens+=d.tokens.output||0;totalTokens+=d.tokens.total||0;cost+=d.tokens.costUsd||0}if(d.status==='completed')done++;if(d.status==='error')failed++;$('#focus').textContent=d.name;$('#message').textContent=d.message||'';log(d.name,d.status==='completed'?`Concluído • ${(d.tokens?.total||0).toLocaleString('pt-BR')} tokens • ativação consolidada.`:`Falha: ${d.message}`);wave();update()});
stream.addEventListener('handoff',e=>{const d=JSON.parse(e.data);log('DATA FLOW',`${String(d.from).toUpperCase()} → próximo agente • onda de informação propagada`);wave();});
stream.addEventListener('coordinator',e=>{const d=JSON.parse(e.data);if(d.tokens){inputTokens+=d.tokens.input||0;outputTokens+=d.tokens.output||0;totalTokens+=d.tokens.total||0;cost+=d.tokens.costUsd||0}$('#focus').textContent='NEXUS';$('#message').textContent=d.output||'Consolidação concluída.';log('NEXUS',`Consolidação finalizada • ${d.tokens?.total||0} tokens`);wave();update()});
stream.addEventListener('error',e=>{let d={};try{d=JSON.parse(e.data)}catch{}if(d.message){log('ERRO',d.message);failed++}$('#live').textContent='● OPERATION ERROR';$('#live').style.color='#ff667a';$('#run').disabled=false;stream?.close();update()});stream.addEventListener('campaign',e=>{const d=JSON.parse(e.data);if(d.status==='completed'||d.status==='completed_with_errors'){$('#run').disabled=false;$('#live').textContent=d.status==='completed'?'● COMPLETE':'● COMPLETE WITH ERRORS';$('#live').style.color=d.status==='completed'?'#61f2a5':'#ffc857';stream?.close()}})};setInterval(update,1000);